### ISSUE TITLE
Can we make common part for html and svg properties?

### ISSUE THREAD

**Issue by denisx** [wooorm/property-information#22]
It will save 2kb (1kb zip)

**Comment by wooorm** [comment]
?

Please provide more info

**Comment by denisx** [comment]
html and svg has ~100 identical properties. i want to make a pr, to make a common part for it. what do you think?

**Comment by wooorm** [comment]
I doubt it? Can you please explain how you came to those numbers? Please show code for what you did? I doubt that there would be such a difference in GZip?

**Comment by denisx** [comment]
This is common part:
```
// var properties = {
className: spaceSeparated,
content: null,
crossOrigin: null,
href: null,
hrefLang: null,
id: null,
lang: null,
max: null,
media: null,
method: null,
min: null,
name: null,
onAbort: null,
onAfterPrint: null,
onBeforePrint: null,
onCancel: null,
onCanPlay: null,
onCanPlayThrough: null,
onChange: null,
onClick: null,
onClose: null,
onCopy: null,
onCueChange: null,
onCut: null,
onDblClick: null,
onDrag: null,
onDragEnd: null,
onDragEnter: null,
onDragExit: null,
onDragLeave: null,
onDragOver: null,
onDragStart: null,
onDrop: null,
onDurationChange: null,
onEmptied: null,
onEnded: null,
onError: null,
onFocus: null,
onHashChange: null,
onInput: null,
onInvalid: null,
onKeyDown: null,
onKeyPress: null,
onKeyUp: null,
onLoad: null,
onLoadedData: null,
onLoadedMetadata: null,
onLoadStart: null,
onMessage: null,
onMouseDown: null,
onMouseEnter: null,
onMouseLeave: null,
onMouseMove: null,
onMouseOut: null,
onMouseOver: null,
onMouseUp: null,
onOffline: null,
onOnline: null,
onPageHide: null,
onPageShow: null,
onPaste: null,
onPause: null,
onPlay: null,
onPlaying: null,
onPopState: null,
onProgress: null,
onRateChange: null,
onReset: null,
onResize: null,
onScroll: null,
onSeeked: null,
onSeeking: null,
onSelect: null,
onStalled: null,
onStorage: null,
onSubmit: null,
onSuspend: null,
onTimeUpdate: null,
onToggle: null,
onUnload: null,
onVolumeChange: null,
onWaiting: null,
ping: spaceSeparated,
referrerPolicy: null,
style: null,
tabIndex: number,
target: null,
title: null,
type: null,
//}
```
it is 2kb raw or 1kb zip

**Comment by wooorm** [comment]
I thought you were talking about something else. It seems you are talking about a custom list, your own list, of things you believe are often used.

This list is very small. If it was used in the unified collective, it would break many tests across the projects.

unified works because it supports *all* of markdown and html and css and svg and such. It follows standards. I don’t want to break standards.

**Comment by denisx** [comment]
I say about patch adds, no majority changes.
vision:
now: svg, html files
future: svg+common import, html+common import.

they will have the same content as today. But some optimized by size, if you use both files at code. I think no test must be broken.

of course it is just discussion

**Comment by wooorm** [comment]
> vision

I doubt this vision: gzip already does what you want.
Feel free to test your idea locally and if it works, report back.
I don’t think it will be smaller.

**Comment by denisx** [comment]
this code `import {html} from ...` does the same result, yes
this code `import {html, svg} from ...` will have less result. because they will have common import

**Comment by denisx** [comment]
... yes, it is all about raw size. zip will have not big numbers.

tnx
